### ISSUE TITLE
Email validation could treat real emails as incorrect.

### ISSUE THREAD

**Issue by tiagorangel2011** [nopwdio/sdk-js#8]
The email validation system treats longer email tlds as incorrect, although they exist and can be used.

**Comment by apinet** [comment]
Hi Tiago, thank you for raising this issue. Can you specify an example of a domain for which it does not work?

**Comment by tiagorangel2011** [comment]
This is a very minor issue, but for example emails like ***@***.***
or ***@***.*** (yes .academy and .agency are real tlds, you can see
more at
https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains#ICANN-era_generic_top-level_domains),
will not work.

Btw thanks for making nopwd, it's awesome :)

Adrien Pinet ***@***.***> escreveu (domingo, 31/03/2024 à(s)
08:02):

**Comment by apinet** [comment]
We do indeed verify whether the email address is correctly formatted, and our checks do allow the use of generic top-level domains (TLDs). However, we also test whether the domain used is properly associated with a valid mail server. I believe the error encountered may be due to the fact that during the input of your email address, it was not linked to an actual mail server.

Thank you for your feedback btw and glad to see happy users ;)
